# Automatically generated by Pynguin.
import pytest
import aeneas.syncmap.smfxml as module_0

def test_case_0():
    sync_map_format_x_m_l_0 = module_0.SyncMapFormatXML()
    assert module_0.SyncMapFormatXML.TAG == 'SyncMapFormatXML'
    assert module_0.SyncMapFormatXML.DEFAULT == 'xml'

@pytest.mark.xfail(strict=True)
def test_case_1():
    sync_map_format_x_m_l_0 = module_0.SyncMapFormatXML()
    assert module_0.SyncMapFormatXML.TAG == 'SyncMapFormatXML'
    assert module_0.SyncMapFormatXML.DEFAULT == 'xml'
    sync_map_format_x_m_l_0.format(sync_map_format_x_m_l_0)