# Automatically generated by Pynguin.
import pytest
import aeneas.syncmap.smfbase as module_0

def test_case_0():
    sync_map_format_base_0 = module_0.SyncMapFormatBase()
    assert f'{type(sync_map_format_base_0.logger).__module__}.{type(sync_map_format_base_0.logger).__qualname__}' == 'aeneas.logger.Logger'
    assert len(sync_map_format_base_0.logger) == 0
    assert f'{type(sync_map_format_base_0.rconf).__module__}.{type(sync_map_format_base_0.rconf).__qualname__}' == 'aeneas.runtimeconfiguration.RuntimeConfiguration'
    assert sync_map_format_base_0.variant is None
    assert sync_map_format_base_0.parameters is None
    assert module_0.SyncMapFormatBase.TAG == 'SyncMapFormatBase'

@pytest.mark.xfail(strict=True)
def test_case_1():
    sync_map_format_base_0 = module_0.SyncMapFormatBase()
    assert f'{type(sync_map_format_base_0.logger).__module__}.{type(sync_map_format_base_0.logger).__qualname__}' == 'aeneas.logger.Logger'
    assert len(sync_map_format_base_0.logger) == 0
    assert f'{type(sync_map_format_base_0.rconf).__module__}.{type(sync_map_format_base_0.rconf).__qualname__}' == 'aeneas.runtimeconfiguration.RuntimeConfiguration'
    assert sync_map_format_base_0.variant is None
    assert sync_map_format_base_0.parameters is None
    assert module_0.SyncMapFormatBase.TAG == 'SyncMapFormatBase'
    bytes_0 = b'\xda|\x88'
    sync_map_format_base_0.parse(bytes_0, sync_map_format_base_0)

@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    sync_map_format_base_0 = module_0.SyncMapFormatBase(none_type_0, rconf=none_type_0)
    assert f'{type(sync_map_format_base_0.logger).__module__}.{type(sync_map_format_base_0.logger).__qualname__}' == 'aeneas.logger.Logger'
    assert len(sync_map_format_base_0.logger) == 0
    assert f'{type(sync_map_format_base_0.rconf).__module__}.{type(sync_map_format_base_0.rconf).__qualname__}' == 'aeneas.runtimeconfiguration.RuntimeConfiguration'
    assert sync_map_format_base_0.variant is None
    assert sync_map_format_base_0.parameters is None
    assert module_0.SyncMapFormatBase.TAG == 'SyncMapFormatBase'
    sync_map_format_base_1 = module_0.SyncMapFormatBase()
    assert f'{type(sync_map_format_base_1.logger).__module__}.{type(sync_map_format_base_1.logger).__qualname__}' == 'aeneas.logger.Logger'
    assert len(sync_map_format_base_1.logger) == 0
    assert f'{type(sync_map_format_base_1.rconf).__module__}.{type(sync_map_format_base_1.rconf).__qualname__}' == 'aeneas.runtimeconfiguration.RuntimeConfiguration'
    assert sync_map_format_base_1.variant is None
    assert sync_map_format_base_1.parameters is None
    sync_map_format_base_2 = module_0.SyncMapFormatBase(rconf=sync_map_format_base_1)
    assert f'{type(sync_map_format_base_2.logger).__module__}.{type(sync_map_format_base_2.logger).__qualname__}' == 'aeneas.logger.Logger'
    assert len(sync_map_format_base_2.logger) == 0
    assert f'{type(sync_map_format_base_2.rconf).__module__}.{type(sync_map_format_base_2.rconf).__qualname__}' == 'aeneas.syncmap.smfbase.SyncMapFormatBase'
    assert sync_map_format_base_2.variant is None
    assert sync_map_format_base_2.parameters is None
    sync_map_format_base_0.format(sync_map_format_base_0)