# Automatically generated by Pynguin.
import pdir.format as module_0
import pdir.attr_category as module_1
import ast as module_2
import pdir.api as module_3


def test_case_0():
    list_0 = []
    str_0 = module_0.format_pattrs(list_0)


def test_case_1():
    module_0._AttributeGroupFormatter()


def test_case_2():
    str_0 = "+ShE0NK9tMJ+"
    attr_category_0 = module_1.AttrCategory.STATIC_METHOD
    precedence_0 = module_2._Precedence.YIELD
    tuple_0 = (attr_category_0, precedence_0)
    pretty_attribute_0 = module_3.PrettyAttribute(str_0, tuple_0, attr_category_0)
    list_0 = [
        pretty_attribute_0,
        pretty_attribute_0,
        pretty_attribute_0,
        pretty_attribute_0,
    ]
    str_1 = module_0.format_pattrs(list_0)


def test_case_3():
    str_0 = "tBHpU"
    attr_category_0 = module_1.AttrCategory.PICKLE
    tuple_0 = (attr_category_0, attr_category_0)
    pretty_attribute_0 = module_3.PrettyAttribute(str_0, tuple_0, str_0)
    str_1 = pretty_attribute_0.get_oneline_doc()
    list_0 = [pretty_attribute_0, pretty_attribute_0, pretty_attribute_0]
    str_2 = pretty_attribute_0.get_oneline_doc()
    str_3 = module_0.format_pattrs(list_0)
    str_4 = module_0.format_pattrs(list_0)
    str_5 = module_0.format_pattrs(list_0)
    and_0 = module_2.And()
    module_0._AttributeGroupFormatter()


def test_case_4():
    str_0 = "tBHpU"
    str_1 = "td>6O\r)"
    attr_category_0 = module_1.AttrCategory.SLOT
    attr_category_1 = module_1.AttrCategory.PICKLE
    tuple_0 = (attr_category_0, attr_category_1)
    pretty_attribute_0 = module_3.PrettyAttribute(str_1, tuple_0, str_0)
    str_2 = pretty_attribute_0.get_oneline_doc()
    list_0 = [pretty_attribute_0, pretty_attribute_0, pretty_attribute_0]
    str_3 = module_0.format_pattrs(list_0)
    dict_0 = {}
    module_0._AttributeGroupFormatter(**dict_0)


def test_case_5():
    str_0 = "+ShE0NK9tMJ+"
    attr_category_0 = module_1.AttrCategory.STATIC_METHOD
    precedence_0 = module_2._Precedence.TUPLE
    tuple_0 = (attr_category_0, precedence_0)
    pretty_attribute_0 = module_3.PrettyAttribute(str_0, tuple_0, attr_category_0)
    list_0 = [
        pretty_attribute_0,
        pretty_attribute_0,
        pretty_attribute_0,
        pretty_attribute_0,
    ]
    str_1 = module_0.format_pattrs(list_0)
