/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 03 15:44:34 GMT 2022
 */

package spark.route;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import spark.route.RouteMatcher;
import spark.route.RouteMatcherFactory;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RouteMatcherFactory_ESTest extends RouteMatcherFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RouteMatcher routeMatcher0 = RouteMatcherFactory.get();
      RouteMatcher routeMatcher1 = RouteMatcherFactory.get();
      assertSame(routeMatcher1, routeMatcher0);
  }
}
