/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 21 03:33:15 GMT 2022
 */

package com.contentful.java.cda.rich;

import org.junit.Test;
import static org.junit.Assert.*;
import com.contentful.java.cda.rich.CDARichNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CDARichNode_ESTest extends CDARichNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CDARichNode cDARichNode0 = new CDARichNode();
  }
}
