/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 06 18:47:53 GMT 2022
 */

package com.imadcn.framework.idworker.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.imadcn.framework.idworker.exception.RegExceptionHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RegExceptionHandler_ESTest extends RegExceptionHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RegExceptionHandler.handleException((Exception) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockException mockException0 = new MockException();
      // Undeclared exception!
      try { 
        RegExceptionHandler.handleException(mockException0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/zookeeper/KeeperException$ConnectionLossException
         //
         verifyException("com.imadcn.framework.idworker.exception.RegExceptionHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RegExceptionHandler regExceptionHandler0 = new RegExceptionHandler();
  }
}
