# Automatically generated by Pynguin.
import pytest
import sundry.dataclass_chain as module_0

@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 8
    module_0.dataclass_chain(int_0, *int_0)