/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 11 18:46:46 GMT 2022
 */

package org.trendafilov.confucius.core;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.NoSuchFileException;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.trendafilov.confucius.core.FileConfigurationDataProvider;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FileConfigurationDataProvider_ESTest extends FileConfigurationDataProvider_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("org.trendafilov.confucius.core.FileConfigurationDataProvider");
      byte[] byteArray0 = new byte[6];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      FileConfigurationDataProvider fileConfigurationDataProvider0 = new FileConfigurationDataProvider("org.trendafilov.confucius.core.FileConfigurationDataProvider");
      InputStream inputStream0 = fileConfigurationDataProvider0.getInputStream();
      assertEquals(6, inputStream0.available());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileConfigurationDataProvider fileConfigurationDataProvider0 = new FileConfigurationDataProvider("org.trendafilov.confucius.core.FileConfigurationDataProvider");
      try { 
        fileConfigurationDataProvider0.getInputStream();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FileConfigurationDataProvider fileConfigurationDataProvider0 = new FileConfigurationDataProvider("?");
      try { 
        fileConfigurationDataProvider0.getAllLines();
        fail("Expecting exception: NoSuchFileException");
      
      } catch(NoSuchFileException e) {
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FileConfigurationDataProvider fileConfigurationDataProvider0 = new FileConfigurationDataProvider((String) null);
      List<String> list0 = fileConfigurationDataProvider0.getAllLines();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FileConfigurationDataProvider fileConfigurationDataProvider0 = new FileConfigurationDataProvider((String) null);
      // Undeclared exception!
      try { 
        fileConfigurationDataProvider0.getInputStream();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FileConfigurationDataProvider fileConfigurationDataProvider0 = new FileConfigurationDataProvider("");
      try { 
        fileConfigurationDataProvider0.getAllLines();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
      }
  }
}
