/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 09 08:24:05 GMT 2022
 */

package com.easyinnova.tiff.model.types;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.easyinnova.tiff.model.TagValue;
import com.easyinnova.tiff.model.types.SubIFD;
import com.easyinnova.tiff.model.types.abstractTiffType;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SubIFD_ESTest extends SubIFD_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SubIFD subIFD0 = new SubIFD();
      TagValue tagValue0 = new TagValue((-592), 88);
      subIFD0.addTag(tagValue0);
      subIFD0.toString();
      assertTrue(subIFD0.isIFD());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SubIFD subIFD0 = new SubIFD();
      TagValue tagValue0 = new TagValue(766, 766);
      LinkedList<abstractTiffType> linkedList0 = new LinkedList<abstractTiffType>();
      linkedList0.add((abstractTiffType) null);
      tagValue0.setValue(linkedList0);
      subIFD0.addTag(tagValue0);
      // Undeclared exception!
      try { 
        subIFD0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SubIFD subIFD0 = new SubIFD();
      subIFD0.toString();
      assertTrue(subIFD0.isIFD());
  }
}
