/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 05 15:49:48 GMT 2022
 */

package org.jfaster.mango.crud.named.parser.op;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfaster.mango.crud.named.parser.op.GreaterThanEqualOp;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GreaterThanEqualOp_ESTest extends GreaterThanEqualOp_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GreaterThanEqualOp greaterThanEqualOp0 = new GreaterThanEqualOp();
      String string0 = greaterThanEqualOp0.keyword();
      assertEquals("GreaterThanEqual", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GreaterThanEqualOp greaterThanEqualOp0 = new GreaterThanEqualOp();
      String string0 = greaterThanEqualOp0.operator();
      assertEquals(">=", string0);
  }
}
