/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 06 12:41:18 GMT 2022
 */

package com.fedapay.utile;

import org.junit.Test;
import static org.junit.Assert.*;
import com.fedapay.utile.CustomerModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CustomerModel_ESTest extends CustomerModel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CustomerModel customerModel0 = new CustomerModel();
  }
}
