/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 05 16:17:15 GMT 2022
 */

package org.jfaster.mango.jdbc.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfaster.mango.jdbc.exception.BadSqlGrammarException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BadSqlGrammarException_ESTest extends BadSqlGrammarException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BadSqlGrammarException badSqlGrammarException0 = new BadSqlGrammarException("; ");
      BadSqlGrammarException badSqlGrammarException1 = new BadSqlGrammarException("OB.'9", badSqlGrammarException0);
      assertFalse(badSqlGrammarException1.equals((Object)badSqlGrammarException0));
  }
}
