/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 18 04:20:01 GMT 2022
 */

package org.dnal.compiler.impoter;

import org.junit.Test;
import static org.junit.Assert.*;
import org.dnal.api.CompilerOptions;
import org.dnal.api.impl.CompilerContext;
import org.dnal.compiler.impoter.MockImportLoader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MockImportLoader_ESTest extends MockImportLoader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockImportLoader mockImportLoader0 = new MockImportLoader();
      CompilerOptions compilerOptions0 = new CompilerOptions();
      CompilerContext compilerContext0 = new CompilerContext("", (Integer) null, mockImportLoader0, (String) null, compilerOptions0);
      mockImportLoader0.importPackage("", compilerContext0);
  }
}
