/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 08 18:34:03 GMT 2022
 */

package com.inspiring.pugtsdb.bean;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.inspiring.pugtsdb.bean.Point;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Point_ESTest extends Point_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Point<Integer> point0 = Point.of((-3223L), integer0);
      assertEquals((-3223L), point0.getTimestamp());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object object0 = new Object();
      Point<Object> point0 = Point.of(1L, object0);
      point0.getValue();
      assertEquals(1L, point0.getTimestamp());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer((-196));
      Point<Integer> point0 = new Point<Integer>(0L, integer0);
      long long0 = point0.getTimestamp();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Point<Integer> point0 = new Point<Integer>((-1L), integer0);
      long long0 = point0.getTimestamp();
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Point<Object> point0 = null;
      try {
        point0 = new Point<Object>((-16), (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Point value cannot be null
         //
         verifyException("com.inspiring.pugtsdb.bean.Point", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        Point.of((long) 0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Point value cannot be null
         //
         verifyException("com.inspiring.pugtsdb.bean.Point", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Point<Integer> point0 = new Point<Integer>((-1L), integer0);
      String string0 = point0.toString();
      assertEquals("Point{timestamp=-1, value=0}", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Point<Integer> point0 = Point.of(0L, integer0);
      assertEquals(0L, point0.getTimestamp());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Point<Object> point0 = new Point<Object>(1L, integer0);
      long long0 = point0.getTimestamp();
      assertEquals(1L, long0);
  }
}
