/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 20 10:30:51 GMT 2022
 */

package com.github.shootercheng.export.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.shootercheng.export.utils.ExportStringUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ExportStringUtils_ESTest extends ExportStringUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = ExportStringUtils.isEmpty("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = ExportStringUtils.isEmpty("1=qqotwg");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      boolean boolean0 = ExportStringUtils.isEmpty((String) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ExportStringUtils exportStringUtils0 = new ExportStringUtils();
  }
}
