/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 26 01:11:09 GMT 2022
 */

package jp.co.yahoo.yosegi.inmemory;

import org.junit.Test;
import static org.junit.Assert.*;
import jp.co.yahoo.yosegi.inmemory.YosegiNullLoader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class YosegiNullLoader_ESTest extends YosegiNullLoader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      YosegiNullLoader yosegiNullLoader0 = new YosegiNullLoader(0);
      int int0 = yosegiNullLoader0.getLoadSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      YosegiNullLoader yosegiNullLoader0 = new YosegiNullLoader(15);
      int int0 = yosegiNullLoader0.getLoadSize();
      assertEquals(15, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      YosegiNullLoader yosegiNullLoader0 = new YosegiNullLoader(0);
      yosegiNullLoader0.getLoaderType();
      assertEquals(0, yosegiNullLoader0.getLoadSize());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      YosegiNullLoader yosegiNullLoader0 = new YosegiNullLoader((-918));
      yosegiNullLoader0.build();
      assertEquals((-918), yosegiNullLoader0.getLoadSize());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      YosegiNullLoader yosegiNullLoader0 = new YosegiNullLoader((-918));
      yosegiNullLoader0.finish();
      assertEquals((-918), yosegiNullLoader0.getLoadSize());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      YosegiNullLoader yosegiNullLoader0 = new YosegiNullLoader((-918));
      int int0 = yosegiNullLoader0.getLoadSize();
      assertEquals((-918), int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      YosegiNullLoader yosegiNullLoader0 = new YosegiNullLoader((-918));
      boolean boolean0 = yosegiNullLoader0.isLoadingSkipped();
      assertTrue(boolean0);
      assertEquals((-918), yosegiNullLoader0.getLoadSize());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      YosegiNullLoader yosegiNullLoader0 = new YosegiNullLoader((-735));
      yosegiNullLoader0.setNull((-735));
      assertEquals((-735), yosegiNullLoader0.getLoadSize());
  }
}
