/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 31 18:52:09 GMT 2022
 */

package org.hswebframework.utils.file;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.hswebframework.utils.file.EncodingDetect;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EncodingDetect_ESTest extends EncodingDetect_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        EncodingDetect.getJavaEncode("F,_`#^>pF}:q");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("org.hswebframework.utils.file.BytesEncodingDetect", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EncodingDetect encodingDetect0 = new EncodingDetect();
  }
}
