/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 31 22:31:51 GMT 2022
 */

package com.hubspot.jinjava.lib.exptest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.hubspot.jinjava.interpret.JinjavaInterpreter;
import com.hubspot.jinjava.lib.exptest.IsLowerExpTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IsLowerExpTest_ESTest extends IsLowerExpTest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IsLowerExpTest isLowerExpTest0 = new IsLowerExpTest();
      Object[] objectArray0 = new Object[5];
      // Undeclared exception!
      try { 
        isLowerExpTest0.evaluate("lower", (JinjavaInterpreter) null, objectArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("com.hubspot.jinjava.lib.exptest.IsLowerExpTest", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IsLowerExpTest isLowerExpTest0 = new IsLowerExpTest();
      Object object0 = new Object();
      Object[] objectArray0 = new Object[5];
      boolean boolean0 = isLowerExpTest0.evaluateNegated(object0, (JinjavaInterpreter) null, objectArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IsLowerExpTest isLowerExpTest0 = new IsLowerExpTest();
      Object[] objectArray0 = new Object[5];
      boolean boolean0 = isLowerExpTest0.evaluate((Object) null, (JinjavaInterpreter) null, objectArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IsLowerExpTest isLowerExpTest0 = new IsLowerExpTest();
      String string0 = isLowerExpTest0.getName();
      assertEquals("lower", string0);
  }
}
