# Automatically generated by Pynguin.
import pytest
import jtop.core.exceptions as module_0

def test_case_0():
    float_0 = -800.47819
    jtop_exception_0 = module_0.JtopException(float_0)
    assert jtop_exception_0.message == pytest.approx(-800.47819, abs=0.01, rel=0.01)
    assert jtop_exception_0.errors == ''
    var_0 = jtop_exception_0.__str__()
    assert var_0 == '-800.47819'
    var_1 = var_0.__repr__()
    assert var_1 == "'-800.47819'"

def test_case_1():
    bool_0 = True
    jtop_exception_0 = module_0.JtopException(bool_0)
    assert jtop_exception_0.message is True
    assert jtop_exception_0.errors == ''
    var_0 = jtop_exception_0.__repr__()
    assert var_0 == 'True'
    var_1 = var_0.__str__()
    assert var_1 == 'True'
    var_2 = var_1.__str__()
    assert var_2 == 'True'