# Automatically generated by Pynguin.
import httpie.output.processing as module_0


def test_case_0():
    conversion_0 = module_0.Conversion()
    str_0 = 'xtLX~>#/gdrQ4^]"Oq-'
    none_type_0 = conversion_0.get_converter(str_0)


def test_case_1():
    str_0 = "=@"
    list_0 = []
    conversion_0 = module_0.Conversion()
    none_type_0 = module_0.is_valid_mime(str_0)
    formatting_0 = module_0.Formatting(list_0, str_0)
    dict_0 = {}
    formatting_1 = module_0.Formatting(list_0)
    str_1 = formatting_1.format_body(str_0, none_type_0)
    str_2 = formatting_1.format_body(str_0, str_0)
    formatting_2 = module_0.Formatting(list_0, list_0, **dict_0)
    str_3 = "X>D:)h0ZCAqc0&*wxFj"
    none_type_1 = conversion_0.get_converter(str_3)
    str_4 = formatting_2.format_headers(str_0)


def test_case_2():
    conversion_0 = module_0.Conversion()
    str_0 = "Output Options"
    none_type_0 = conversion_0.get_converter(str_0)


def test_case_3():
    str_0 = "colors"
    list_0 = [str_0, str_0, str_0, str_0, str_0]
    module_0.Formatting(list_0)


def test_case_4():
    str_0 = "We&\x0bFst?t#h"
    list_0 = []
    formatting_0 = module_0.Formatting(list_0)
    str_1 = formatting_0.format_headers(str_0)


def test_case_5():
    str_0 = "Y=GA;A0?D)C\tN'g[3"
    str_1 = "GET"
    list_0 = []
    formatting_0 = module_0.Formatting(list_0)
    str_2 = formatting_0.format_body(str_0, str_1)


def test_case_6():
    str_0 = "TX/["
    list_0 = []
    formatting_0 = module_0.Formatting(list_0, list_0)
    str_1 = formatting_0.format_body(str_0, str_0)
