/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 03 20:50:56 GMT 2022
 */

package info.michaelwittig.javaq.query.column.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import info.michaelwittig.javaq.query.column.impl.FloatColumn;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FloatColumn_ESTest extends FloatColumn_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FloatColumn floatColumn0 = new FloatColumn("info.michaelwittig.javaq.query.column.impl.IntegerColumn");
      assertEquals("info.michaelwittig.javaq.query.column.impl.IntegerColumn", floatColumn0.getName());
  }
}
