/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 29 18:11:36 GMT 2022
 */

package io.github.jakaarl.iban;

import org.junit.Test;
import static org.junit.Assert.*;
import io.github.jakaarl.iban.InvalidIbanException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class InvalidIbanException_ESTest extends InvalidIbanException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InvalidIbanException invalidIbanException0 = new InvalidIbanException("");
  }
}
