/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 04 18:02:54 GMT 2022
 */

package com.rtfparserkit.parser.raw;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rtfparserkit.parser.raw.ByteBuffer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ByteBuffer_ESTest extends ByteBuffer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ByteBuffer byteBuffer0 = new ByteBuffer();
      byteBuffer0.add((-1549));
      byteBuffer0.toArray();
      assertFalse(byteBuffer0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ByteBuffer byteBuffer0 = new ByteBuffer();
      boolean boolean0 = byteBuffer0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ByteBuffer byteBuffer0 = new ByteBuffer();
      assertTrue(byteBuffer0.isEmpty());
      
      byteBuffer0.add((-1549));
      boolean boolean0 = byteBuffer0.isEmpty();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ByteBuffer byteBuffer0 = new ByteBuffer();
      byteBuffer0.clear();
      assertTrue(byteBuffer0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ByteBuffer byteBuffer0 = new ByteBuffer();
      String string0 = byteBuffer0.toString();
      assertEquals("[ByteBuffer bufferSize=0 buffer=]", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ByteBuffer byteBuffer0 = new ByteBuffer();
      byte[] byteArray0 = byteBuffer0.toArray();
      assertEquals(0, byteArray0.length);
  }
}
