/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 11 23:13:13 GMT 2022
 */

package org.gedcom4j.writer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.gedcom4j.model.ChangeDate;
import org.gedcom4j.model.Gedcom;
import org.gedcom4j.writer.ChangeDateEmitter;
import org.gedcom4j.writer.GedcomWriter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ChangeDateEmitter_ESTest extends ChangeDateEmitter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Gedcom gedcom0 = new Gedcom();
      GedcomWriter gedcomWriter0 = new GedcomWriter(gedcom0);
      ChangeDate changeDate0 = new ChangeDate();
      changeDate0.setDate("systemId");
      ChangeDateEmitter changeDateEmitter0 = new ChangeDateEmitter(gedcomWriter0, (-3390), changeDate0);
      changeDateEmitter0.emit();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Gedcom gedcom0 = new Gedcom();
      GedcomWriter gedcomWriter0 = new GedcomWriter(gedcom0);
      ChangeDateEmitter changeDateEmitter0 = new ChangeDateEmitter(gedcomWriter0, 0, (ChangeDate) null);
      changeDateEmitter0.emit();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Gedcom gedcom0 = new Gedcom();
      GedcomWriter gedcomWriter0 = new GedcomWriter(gedcom0);
      ChangeDate changeDate0 = new ChangeDate();
      ChangeDateEmitter changeDateEmitter0 = new ChangeDateEmitter(gedcomWriter0, (-3390), changeDate0);
      try { 
        changeDateEmitter0.emit();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Required value for tag DATE at level -3389 was null or blank
         //
         verifyException("org.gedcom4j.writer.AbstractEmitter", e);
      }
  }
}
