/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 03 17:18:08 GMT 2022
 */

package com.github.relayjdbc.command;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.relayjdbc.command.NullCallingContextFactory;
import com.github.relayjdbc.serial.CallingContext;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NullCallingContextFactory_ESTest extends NullCallingContextFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NullCallingContextFactory nullCallingContextFactory0 = new NullCallingContextFactory();
      CallingContext callingContext0 = nullCallingContextFactory0.create();
      assertNull(callingContext0);
  }
}
