/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 05 16:24:07 GMT 2022
 */

package org.jfaster.mango.transaction.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.jfaster.mango.transaction.exception.CannotGetJdbcConnectionException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CannotGetJdbcConnectionException_ESTest extends CannotGetJdbcConnectionException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CannotGetJdbcConnectionException cannotGetJdbcConnectionException0 = new CannotGetJdbcConnectionException("p[)U_J/");
      MockThrowable mockThrowable0 = new MockThrowable(cannotGetJdbcConnectionException0);
      CannotGetJdbcConnectionException cannotGetJdbcConnectionException1 = new CannotGetJdbcConnectionException("p[)U_J/", mockThrowable0);
      assertFalse(cannotGetJdbcConnectionException1.equals((Object)cannotGetJdbcConnectionException0));
  }
}
