/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 14 00:20:18 GMT 2022
 */

package de.javawi.jstun.header;

import org.junit.Test;
import static org.junit.Assert.*;
import de.javawi.jstun.header.MessageHeaderException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MessageHeaderException_ESTest extends MessageHeaderException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MessageHeaderException messageHeaderException0 = new MessageHeaderException("");
  }
}
