/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Oct 26 01:02:05 GMT 2022
 */

package jp.co.yahoo.yosegi.reader;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class WrapReader_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "jp.co.yahoo.yosegi.reader.WrapReader"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/user"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(WrapReader_ESTest_scaffolding.class.getClassLoader() ,
      "jp.co.yahoo.yosegi.spread.Spread",
      "jp.co.yahoo.yosegi.block.IBlockReader",
      "jp.co.yahoo.yosegi.reader.YosegiReader",
      "jp.co.yahoo.yosegi.config.Configuration",
      "jp.co.yahoo.yosegi.spread.expression.IExpressionNode",
      "jp.co.yahoo.yosegi.reader.WrapReader",
      "jp.co.yahoo.yosegi.inmemory.IRawConverter",
      "jp.co.yahoo.yosegi.stats.SummaryStats"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(WrapReader_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "jp.co.yahoo.yosegi.reader.WrapReader",
      "jp.co.yahoo.yosegi.reader.YosegiReader",
      "jp.co.yahoo.yosegi.config.Configuration",
      "jp.co.yahoo.yosegi.spread.expression.NotExpressionNode",
      "jp.co.yahoo.yosegi.spread.expression.StringExtractNode",
      "jp.co.yahoo.yosegi.spread.column.filter.PartialMatchStringFilter",
      "jp.co.yahoo.yosegi.spread.expression.ExecuterNode",
      "jp.co.yahoo.yosegi.spread.expression.OrExpressionNode",
      "jp.co.yahoo.yosegi.util.io.InputStreamUtils",
      "jp.co.yahoo.yosegi.spread.expression.AndExpressionNode",
      "jp.co.yahoo.yosegi.spread.column.filter.LeStringCompareFilter",
      "jp.co.yahoo.yosegi.spread.column.filter.BackwardMatchStringFilter",
      "jp.co.yahoo.yosegi.blockindex.BlockIndexNode",
      "jp.co.yahoo.yosegi.util.FindClass",
      "jp.co.yahoo.yosegi.spread.column.filter.RangeStringCompareFilter",
      "jp.co.yahoo.yosegi.spread.column.filter.GeStringCompareFilter",
      "jp.co.yahoo.yosegi.spread.column.filter.LtStringCompareFilter",
      "jp.co.yahoo.yosegi.spread.column.filter.NumberRangeFilter",
      "jp.co.yahoo.yosegi.message.objects.StringObj",
      "jp.co.yahoo.yosegi.message.objects.Utf8BytesLinkObj",
      "jp.co.yahoo.yosegi.spread.column.filter.NumberFilter",
      "jp.co.yahoo.yosegi.spread.column.filter.GtStringCompareFilter"
    );
  }
}
