/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 13 23:19:29 GMT 2022
 */

package com.github.powerlibraries.io.helper.byteout;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.powerlibraries.io.helper.byteout.BAZipOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BAZipOutputStream_ESTest extends BAZipOutputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BAZipOutputStream bAZipOutputStream0 = null;
      try {
        bAZipOutputStream0 = new BAZipOutputStream((OutputStream) null, (ByteArrayOutputStream) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class java.util.zip.Deflater
         //
         verifyException("java.util.zip.ZipOutputStream", e);
      }
  }
}
