/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 17 05:33:07 GMT 2022
 */

package com.dinstone.photon;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.dinstone.photon.ConnectOptions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PhotonOptions_ESTest extends PhotonOptions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConnectOptions connectOptions0 = null;
      try {
        connectOptions0 = new ConnectOptions();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // io/netty/handler/ssl/util/InsecureTrustManagerFactory
         //
         verifyException("com.dinstone.photon.ConnectOptions", e);
      }
  }
}
