/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 05 16:10:49 GMT 2022
 */

package net.imglib2.type.numeric.integer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.math.BigInteger;
import java.nio.ByteBuffer;
import java.nio.ShortBuffer;
import net.imglib2.img.NativeImg;
import net.imglib2.img.basictypeaccess.ShortAccess;
import net.imglib2.img.basictypeaccess.array.DirtyShortArray;
import net.imglib2.img.basictypeaccess.array.ShortArray;
import net.imglib2.img.basictypeaccess.nio.ShortBufferAccess;
import net.imglib2.img.basictypeaccess.volatiles.array.DirtyVolatileShortArray;
import net.imglib2.img.basictypeaccess.volatiles.array.VolatileShortArray;
import net.imglib2.img.sparse.Ntree;
import net.imglib2.img.sparse.ShortNtree;
import net.imglib2.type.NativeTypeFactory;
import net.imglib2.type.PrimitiveType;
import net.imglib2.type.numeric.integer.UnsignedShortType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UnsignedShortType_ESTest extends UnsignedShortType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.setShort((short)1815);
      unsignedShortType0.mul(unsignedShortType0);
      assertEquals(65535.0, unsignedShortType0.getMaxValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = new UnsignedShortType(63);
      assertFalse(unsignedShortType1.equals((Object)unsignedShortType0));
      
      unsignedShortType0.add(unsignedShortType1);
      assertTrue(unsignedShortType1.equals((Object)unsignedShortType0));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      short short0 = UnsignedShortType.getCodedSignedShortChecked(65535);
      assertEquals((short) (-1), short0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      short short0 = UnsignedShortType.getCodedSignedShortChecked(0);
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.setInteger((long) 65506);
      assertEquals(0.0F, unsignedShortType0.getImaginaryFloat(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(588);
      unsignedShortType0.div(unsignedShortType0);
      assertEquals(0.0F, unsignedShortType0.getPhaseFloat(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = UnsignedShortType.getUnsignedShort((short)0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.setInteger((-1450));
      long long0 = unsignedShortType0.getIntegerLong();
      assertEquals(64086L, long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.setShort((short)9);
      int int0 = unsignedShortType0.getInteger();
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      short short0 = UnsignedShortType.getCodedSignedShortChecked(567);
      assertEquals((short)567, short0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      short short0 = UnsignedShortType.getCodedSignedShort((short)0);
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      short short0 = UnsignedShortType.getCodedSignedShort(1855);
      assertEquals((short)1855, short0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      short short0 = UnsignedShortType.getCodedSignedShort((-210));
      assertEquals((short) (-210), short0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.setShort((short)9);
      unsignedShortType0.mul((-1618.1813546654018));
      BigInteger bigInteger0 = unsignedShortType0.getBigInteger();
      assertEquals((byte)28, bigInteger0.byteValue());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.setShort((short)9);
      BigInteger bigInteger0 = unsignedShortType0.getBigInteger();
      assertEquals((byte)9, bigInteger0.byteValue());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.setReal(3007.744F);
      BigInteger bigInteger0 = unsignedShortType0.getBigInteger();
      assertEquals((byte) (-64), bigInteger0.byteValue());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      int int0 = unsignedShortType0.get();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      BigInteger bigInteger0 = BigInteger.ONE;
      unsignedShortType0.setBigInteger(bigInteger0);
      int int0 = unsignedShortType0.get();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.copy();
      assertTrue(unsignedShortType1.equals((Object)unsignedShortType0));
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(588);
      int int0 = unsignedShortType0.compareTo(unsignedShortType0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType((short) (-2708));
      UnsignedShortType unsignedShortType1 = unsignedShortType0.createVariable();
      int int0 = unsignedShortType0.compareTo(unsignedShortType1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(1);
      UnsignedShortType unsignedShortType1 = unsignedShortType0.createVariable();
      int int0 = unsignedShortType1.compareTo(unsignedShortType0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      ByteBuffer byteBuffer0 = ByteBuffer.allocateDirect(0);
      ShortBufferAccess shortBufferAccess0 = ShortBufferAccess.fromByteBuffer(byteBuffer0, true);
      unsignedShortType0.dataAccess = (ShortAccess) shortBufferAccess0;
      // Undeclared exception!
      try { 
        unsignedShortType0.toString();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      short[] shortArray0 = new short[0];
      ShortArray shortArray1 = new ShortArray(shortArray0);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortArray1);
      // Undeclared exception!
      try { 
        unsignedShortType0.toString();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("net.imglib2.img.basictypeaccess.array.AbstractShortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      long[] longArray0 = new long[1];
      Short short0 = new Short((short) (-3120));
      Ntree<Short> ntree0 = new Ntree<Short>(longArray0, short0);
      ShortNtree shortNtree0 = new ShortNtree(ntree0, longArray0);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortNtree0);
      // Undeclared exception!
      unsignedShortType0.sub(unsignedShortType0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      // Undeclared exception!
      try { 
        unsignedShortType0.sub((UnsignedShortType) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.UnsignedShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.setInteger(0L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      short[] shortArray0 = new short[0];
      VolatileShortArray volatileShortArray0 = new VolatileShortArray(shortArray0, true);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(volatileShortArray0);
      // Undeclared exception!
      try { 
        unsignedShortType0.setInteger((long) 65535);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("net.imglib2.img.basictypeaccess.array.AbstractShortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.setInteger(108);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      // Undeclared exception!
      try { 
        unsignedShortType0.setBigInteger((BigInteger) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.UnsignedShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.set(3025);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      ShortArray shortArray0 = new ShortArray(0);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortArray0);
      // Undeclared exception!
      try { 
        unsignedShortType0.set(65535);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("net.imglib2.img.basictypeaccess.array.AbstractShortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType0.mul(unsignedShortType1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      short[] shortArray0 = new short[0];
      DirtyVolatileShortArray dirtyVolatileShortArray0 = new DirtyVolatileShortArray(shortArray0, true);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(dirtyVolatileShortArray0);
      // Undeclared exception!
      try { 
        unsignedShortType0.mul(unsignedShortType0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("net.imglib2.img.basictypeaccess.array.AbstractShortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(567);
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.mul((float) 567);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType((NativeImg<?, ? extends ShortAccess>) null);
      // Undeclared exception!
      try { 
        unsignedShortType0.mul((double) 1004);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      short[] shortArray0 = new short[3];
      ShortBuffer shortBuffer0 = ShortBuffer.wrap(shortArray0, (int) (short)0, 0);
      ShortBufferAccess shortBufferAccess0 = new ShortBufferAccess(shortBuffer0, true);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortBufferAccess0);
      // Undeclared exception!
      try { 
        unsignedShortType0.mul((-446.0));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(1869);
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.inc();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      short[] shortArray0 = new short[0];
      DirtyShortArray dirtyShortArray0 = new DirtyShortArray(shortArray0);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(dirtyShortArray0);
      // Undeclared exception!
      try { 
        unsignedShortType0.inc();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("net.imglib2.img.basictypeaccess.array.AbstractShortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.getIntegerLong();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      ShortBufferAccess shortBufferAccess0 = ShortBufferAccess.fromByteBuffer(byteBuffer0, false);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortBufferAccess0);
      // Undeclared exception!
      try { 
        unsignedShortType0.getIntegerLong();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      short[] shortArray0 = new short[0];
      VolatileShortArray volatileShortArray0 = new VolatileShortArray(shortArray0, true);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(volatileShortArray0);
      // Undeclared exception!
      try { 
        unsignedShortType0.getIntegerLong();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("net.imglib2.img.basictypeaccess.array.AbstractShortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.getInteger();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.getBigInteger();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(1);
      ShortBuffer shortBuffer0 = byteBuffer0.asShortBuffer();
      ShortBufferAccess shortBufferAccess0 = new ShortBufferAccess(shortBuffer0);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortBufferAccess0);
      // Undeclared exception!
      try { 
        unsignedShortType0.getBigInteger();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      short[] shortArray0 = new short[0];
      DirtyShortArray dirtyShortArray0 = new DirtyShortArray(shortArray0);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(dirtyShortArray0);
      // Undeclared exception!
      try { 
        unsignedShortType0.getBigInteger();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("net.imglib2.img.basictypeaccess.array.AbstractShortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.get();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      short[] shortArray0 = new short[0];
      DirtyShortArray dirtyShortArray0 = new DirtyShortArray(shortArray0);
      unsignedShortType0.dataAccess = (ShortAccess) dirtyShortArray0;
      // Undeclared exception!
      try { 
        unsignedShortType0.get();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("net.imglib2.img.basictypeaccess.array.AbstractShortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType0.div(unsignedShortType1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType1.dec();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      byte[] byteArray0 = new byte[0];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      ShortBufferAccess shortBufferAccess0 = new ShortBufferAccess(byteBuffer0);
      unsignedShortType0.dataAccess = (ShortAccess) shortBufferAccess0;
      // Undeclared exception!
      try { 
        unsignedShortType0.copy();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      ShortArray shortArray0 = new ShortArray(0);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortArray0);
      // Undeclared exception!
      try { 
        unsignedShortType0.copy();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("net.imglib2.img.basictypeaccess.array.AbstractShortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      short[] shortArray0 = new short[0];
      ShortBuffer shortBuffer0 = ShortBuffer.wrap(shortArray0);
      ShortBufferAccess shortBufferAccess0 = new ShortBufferAccess(shortBuffer0, false);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortBufferAccess0);
      // Undeclared exception!
      try { 
        unsignedShortType0.compareTo(unsignedShortType0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      ShortBufferAccess shortBufferAccess0 = new ShortBufferAccess(0);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortBufferAccess0);
      // Undeclared exception!
      try { 
        unsignedShortType0.add(unsignedShortType0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      int int0 = UnsignedShortType.getUnsignedShort((short)907);
      assertEquals(907, int0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.set(915);
      unsignedShortType0.mul((float) (-1450));
      assertEquals(0.0, unsignedShortType0.getPhaseDouble(), 0.01);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      ShortBufferAccess shortBufferAccess0 = ShortBufferAccess.fromByteBuffer(byteBuffer0, false);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortBufferAccess0);
      // Undeclared exception!
      try { 
        unsignedShortType0.get();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      short short0 = UnsignedShortType.getCodedSignedShortChecked(65547);
      assertEquals((short) (-1), short0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      short short0 = UnsignedShortType.getCodedSignedShortChecked((-20));
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      // Undeclared exception!
      try { 
        unsignedShortType0.div(unsignedShortType0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("net.imglib2.type.numeric.integer.UnsignedShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      NativeTypeFactory<UnsignedShortType, ShortAccess> nativeTypeFactory0 = unsignedShortType0.getNativeTypeFactory();
      assertEquals(PrimitiveType.SHORT, nativeTypeFactory0.getPrimitiveType());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      double double0 = unsignedShortType0.getMinValue();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.sub(unsignedShortType0);
      assertEquals(0.0, unsignedShortType0.getImaginaryDouble(), 0.01);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      BigInteger bigInteger0 = unsignedShortType0.getBigInteger();
      assertEquals((short)0, bigInteger0.shortValue());
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.dec();
      assertEquals(0.0F, unsignedShortType0.getPhaseFloat(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      UnsignedShortType unsignedShortType1 = unsignedShortType0.duplicateTypeOnSameNativeImg();
      // Undeclared exception!
      try { 
        unsignedShortType0.add(unsignedShortType1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType((ShortAccess) null);
      // Undeclared exception!
      try { 
        unsignedShortType0.copy();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.GenericShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      short[] shortArray0 = new short[0];
      ShortArray shortArray1 = new ShortArray(shortArray0);
      UnsignedShortType unsignedShortType0 = new UnsignedShortType(shortArray1);
      // Undeclared exception!
      try { 
        unsignedShortType0.getInteger();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("net.imglib2.img.basictypeaccess.array.AbstractShortArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      double double0 = unsignedShortType0.getMaxValue();
      assertEquals(65535.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      String string0 = unsignedShortType0.toString();
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      int int0 = unsignedShortType0.getInteger();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      // Undeclared exception!
      try { 
        unsignedShortType0.compareTo((UnsignedShortType) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.imglib2.type.numeric.integer.UnsignedShortType", e);
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      unsignedShortType0.inc();
      assertEquals(0.0, unsignedShortType0.getPhaseDouble(), 0.01);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      UnsignedShortType unsignedShortType0 = new UnsignedShortType();
      long long0 = unsignedShortType0.getIntegerLong();
      assertEquals(0L, long0);
  }
}
