/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 06 21:00:45 GMT 2022
 */

package com.britesnow.snow.web;

import org.junit.Test;
import static org.junit.Assert.*;
import com.britesnow.snow.web.HttpWriterOptions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HttpWriterOptions_ESTest extends HttpWriterOptions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpWriterOptions httpWriterOptions0 = new HttpWriterOptions();
      httpWriterOptions0.setContentType("u>XX_71Wxp @NI ");
      httpWriterOptions0.getContentType();
      assertEquals("UTF-8", httpWriterOptions0.getCharacterEncoding());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpWriterOptions httpWriterOptions0 = new HttpWriterOptions();
      httpWriterOptions0.setCharacterEncoding((String) null);
      String string0 = httpWriterOptions0.getCharacterEncoding();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HttpWriterOptions httpWriterOptions0 = new HttpWriterOptions();
      String string0 = httpWriterOptions0.getCharacterEncoding();
      assertEquals("UTF-8", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HttpWriterOptions httpWriterOptions0 = new HttpWriterOptions();
      httpWriterOptions0.setCharacterEncoding("");
      String string0 = httpWriterOptions0.getCharacterEncoding();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HttpWriterOptions httpWriterOptions0 = new HttpWriterOptions();
      httpWriterOptions0.getContentType();
      assertEquals("UTF-8", httpWriterOptions0.getCharacterEncoding());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      HttpWriterOptions httpWriterOptions0 = new HttpWriterOptions();
      httpWriterOptions0.setContentType("");
      httpWriterOptions0.getContentType();
      assertEquals("UTF-8", httpWriterOptions0.getCharacterEncoding());
  }
}
