/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 08 21:43:36 GMT 2022
 */

package dev.codesoapbox.dummy4j.dummies.identifier.internationalnumber.namenumber;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dev.codesoapbox.dummy4j.DefaultRandomService;
import dev.codesoapbox.dummy4j.Dummy4j;
import dev.codesoapbox.dummy4j.ExpressionResolver;
import dev.codesoapbox.dummy4j.dummies.identifier.internationalnumber.namenumber.BasicIsniProvider;
import dev.codesoapbox.dummy4j.dummies.shared.checkdigitformulas.ModElevenDashTwoFormula;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BasicIsniProvider_ESTest extends BasicIsniProvider_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultRandomService defaultRandomService0 = new DefaultRandomService();
      Dummy4j dummy4j0 = new Dummy4j((ExpressionResolver) null, defaultRandomService0);
      ModElevenDashTwoFormula modElevenDashTwoFormula0 = new ModElevenDashTwoFormula();
      BasicIsniProvider basicIsniProvider0 = new BasicIsniProvider(dummy4j0, modElevenDashTwoFormula0);
      String string0 = basicIsniProvider0.provide();
      assertEquals("0000000000000001", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ModElevenDashTwoFormula modElevenDashTwoFormula0 = new ModElevenDashTwoFormula();
      BasicIsniProvider basicIsniProvider0 = new BasicIsniProvider((Dummy4j) null, modElevenDashTwoFormula0);
      // Undeclared exception!
      try { 
        basicIsniProvider0.provide();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dev.codesoapbox.dummy4j.dummies.identifier.internationalnumber.namenumber.BasicIsniProvider", e);
      }
  }
}
