# Automatically generated by Pynguin.
import pytest
import ns1.rest.transport.base as module_0

@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    module_0.TransportBase(bool_0, bool_0)