/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 02 23:11:49 GMT 2022
 */

package org.raoxunrong.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.raoxunrong.domain.page.CheckablePage;
import org.raoxunrong.utils.HTMLTextLoader;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HTMLTextLoader_ESTest extends HTMLTextLoader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        HTMLTextLoader.getPlainText((CheckablePage) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.raoxunrong.utils.HTMLTextLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HTMLTextLoader hTMLTextLoader0 = new HTMLTextLoader();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        HTMLTextLoader.getText((String) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/jsoup/Jsoup
         //
         verifyException("org.raoxunrong.utils.HTMLTextLoader", e);
      }
  }
}
