/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 06 20:55:50 GMT 2022
 */

package com.britesnow.snow.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.britesnow.snow.util.JAXBProcessor;
import java.lang.reflect.Array;
import java.util.List;
import javax.imageio.metadata.IIOMetadataNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.w3c.dom.Element;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JAXBProcessor_ESTest extends JAXBProcessor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 9);
      Class<Object> class0 = Object.class;
      classArray0[0] = class0;
      classArray0[1] = classArray0[0];
      classArray0[2] = classArray0[1];
      classArray0[3] = class0;
      classArray0[4] = classArray0[0];
      classArray0[5] = classArray0[1];
      classArray0[6] = classArray0[3];
      classArray0[7] = classArray0[0];
      classArray0[8] = class0;
      JAXBProcessor jAXBProcessor0 = new JAXBProcessor(classArray0);
      IIOMetadataNode iIOMetadataNode0 = new IIOMetadataNode((String) null);
      Class<String> class1 = String.class;
      // Undeclared exception!
      try { 
        jAXBProcessor0.getObjectFromXml((Element) iIOMetadataNode0, class1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JAXBProcessor jAXBProcessor0 = new JAXBProcessor();
      IIOMetadataNode iIOMetadataNode0 = new IIOMetadataNode();
      // Undeclared exception!
      try { 
        jAXBProcessor0.getElementFromObject(iIOMetadataNode0, iIOMetadataNode0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.britesnow.snow.util.JAXBProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JAXBProcessor jAXBProcessor0 = null;
      try {
        jAXBProcessor0 = new JAXBProcessor((Class[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.xml.bind.JAXBContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IIOMetadataNode iIOMetadataNode0 = new IIOMetadataNode();
      Class<String>[] classArray0 = (Class<String>[]) Array.newInstance(Class.class, 0);
      JAXBProcessor jAXBProcessor0 = new JAXBProcessor(classArray0);
      try { 
        jAXBProcessor0.getElementFromObject(iIOMetadataNode0, iIOMetadataNode0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // CANNOT_CREATE_XML_FROM_OBJECT  {\"object\":\"javax.imageio.metadata.IIOMetadataNode@6a6d55f3\"}
         //
         verifyException("com.britesnow.snow.util.JAXBProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 0);
      JAXBProcessor jAXBProcessor0 = new JAXBProcessor(classArray0);
      IIOMetadataNode iIOMetadataNode0 = new IIOMetadataNode("ug^#JQ_hkv!9WXSZQZ");
      Class<IIOMetadataNode> class0 = IIOMetadataNode.class;
      try { 
        jAXBProcessor0.getObjectFromXml((Element) iIOMetadataNode0, class0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // CANNOT_CREATE_OBJECT_FROM_XML_ELEMENT
         //
         verifyException("com.britesnow.snow.util.JAXBProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JAXBProcessor jAXBProcessor0 = new JAXBProcessor();
      Class<Object> class0 = Object.class;
      Object object0 = jAXBProcessor0.getObjectFromXml((Element) null, class0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JAXBProcessor jAXBProcessor0 = null;
      try {
        jAXBProcessor0 = new JAXBProcessor((List<Class>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.britesnow.snow.util.JAXBProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Class<String>[] classArray0 = (Class<String>[]) Array.newInstance(Class.class, 0);
      JAXBProcessor jAXBProcessor0 = new JAXBProcessor(classArray0);
      // Undeclared exception!
      try { 
        jAXBProcessor0.getElementFromObject((Object) null, (Element) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // obj parameter must not be null
         //
         verifyException("javax.xml.bind.helpers.AbstractMarshallerImpl", e);
      }
  }
}
